CREATE TABLE PASIEN(
ID_PASIEN INT NOT NULL PRIMARY KEY,
NAMA_PASIEN VARCHAR(50),
JENIS_KELAMIN CHAR(1),
ALAMAT VARCHAR(100),
NO_TELP VARCHAR(13));

CREATE TABLE REKAM_MEDIS(
ID_REKAMMED INT NOT NULL PRIMARY KEY,
ID_PASIEN INT,
DIAGNOSA VARCHAR(50),
TANGGAL_PERIKSA DATE,
FOREIGN KEY (ID_PASIEN) REFERENCES PASIEN(ID_PASIEN));

CREATE TABLE POLI(
ID_POLI INT NOT NULL PRIMARY KEY,
NAMA_POLI VARCHAR(100));

CREATE TABLE DOKTER(
ID_DOKTER INT NOT NULL PRIMARY KEY,
ID_POLI INT,
NAMA_DOKTER VARCHAR(50),
SPESIALIS VARCHAR(50),
ALAMAT VARCHAR(100),
NO_TELP VARCHAR(13),
JADWAL DATE,
FOREIGN KEY (ID_POLI) REFERENCES POLI(ID_POLI));

CREATE TABLE TRANSAKSI(
ID_TRANSAKSI INT NOT NULL PRIMARY KEY,
ID_PASIEN INT,
TANGGAL_TRANSAKSI DATE,
TOTAL_HARGA INTEGER,
METODE_BAYAR VARCHAR(50),
FOREIGN KEY (ID_PASIEN) REFERENCES PASIEN(ID_PASIEN));

CREATE TABLE JENIS_OBAT(
ID_JENIS_OBAT INT NOT NULL PRIMARY KEY,
JENIS_OBAT VARCHAR(50));

CREATE TABLE OBAT(
ID_OBAT INT NOT NULL PRIMARY KEY,
ID_JENIS_OBAT INT,
NAMA_OBAT VARCHAR(500),
HARGA_OBAT INTEGER,
DESKRIPSI_OBAT VARCHAR(500),
STOK_OBAT INTEGER,
FOREIGN KEY (ID_JENIS_OBAT) REFERENCES JENIS_OBAT(ID_JENIS_OBAT));

CREATE TABLE TRANSAKSI_OBAT(
ID_OBAT INT NOT NULL,
ID_TRANSAKSI INT NOT NULL,
CONSTRAINT PK_TRANSAKSI_OBAT PRIMARY KEY(ID_TRANSAKSI, ID_OBAT),
CONSTRAINT FK_OBAT_TRANSAKSI FOREIGN KEY(ID_TRANSAKSI)
REFERENCES TRANSAKSI(ID_TRANSAKSI),
CONSTRAINT FK_TRANSAKSI_OBAT_OBAT FOREIGN KEY(ID_OBAT)
REFERENCES OBAT(ID_OBAT));

CREATE TABLE REKAM_MEDIS_DOKTER(
ID_REKAMMED INT NOT NULL,
ID_DOKTER INT NOT NULL,
CONSTRAINT PK_REKAM_MEDIS_DOKTER PRIMARY KEY(ID_REKAMMED, ID_DOKTER),
CONSTRAINT FK_REKAMMED FOREIGN KEY(ID_REKAMMED) REFERENCES REKAM_MEDIS(ID_REKAMMED),
CONSTRAINT FK_DOKTER FOREIGN KEY(ID_DOKTER) REFERENCES DOKTER(ID_DOKTER));
